ACCOUNT_ID = "736616688306"

CHECK_DEFINITIONS = {
    "ec2": [
        {
            "sort_order": 1,
            "category": "Availability",
            "code": "instance_state",
            "check_item": "Instance state",
            "what_to_verify": "The instance is powered on and usable.",
            "how_to_check": "EC2 instance state from DescribeInstances / console.",
            "success_criteria": "State = running",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 2,
            "category": "Availability",
            "code": "system_status_check",
            "check_item": "System status check",
            "what_to_verify": "AWS host/platform running the instance is healthy.",
            "how_to_check": "CloudWatch metric StatusCheckFailed_System.",
            "success_criteria": "0 (passed)",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 3,
            "category": "Availability",
            "code": "instance_status_check",
            "check_item": "Instance status check",
            "what_to_verify": "The guest OS and instance networking are healthy.",
            "how_to_check": "CloudWatch metric StatusCheckFailed_Instance.",
            "success_criteria": "0 (passed)",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 4,
            "category": "Availability",
            "code": "attached_ebs_status",
            "check_item": "Attached EBS status",
            "what_to_verify": "Attached EBS reachability is healthy.",
            "how_to_check": "CloudWatch metric StatusCheckFailed_AttachedEBS; optionally EBS VolumeStalledIOCheck.",
            "success_criteria": "0 (passed)",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 5,
            "category": "Maintenance",
            "code": "scheduled_events",
            "check_item": "Scheduled events",
            "what_to_verify": "No upcoming reboot, stop, retirement, or maintenance event is pending.",
            "how_to_check": "DescribeInstanceStatus events / EC2 scheduled events.",
            "success_criteria": "No pending critical event",
            "priority": "P1",
            "frequency": "15 min",
        },
        {
            "sort_order": 6,
            "category": "Accessibility",
            "code": "required_ports_reachable",
            "check_item": "Required ports reachable",
            "what_to_verify": "The server answers on the ports you actually use (22/3389/80/443/app port).",
            "how_to_check": "TCP connect from monitoring location or VPC probe.",
            "success_criteria": "Connect succeeds within timeout",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 7,
            "category": "Application",
            "code": "health_url_app_response",
            "check_item": "Health URL / app response",
            "what_to_verify": "The business application is serving requests correctly.",
            "how_to_check": "HTTP/HTTPS GET to /health, /ready, or main endpoint.",
            "success_criteria": "HTTP 200 / expected response body",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 8,
            "category": "Service",
            "code": "process_service_running",
            "check_item": "Process / service running",
            "what_to_verify": "Nginx, Apache, Java, Node, Docker, Windows service, etc. is active.",
            "how_to_check": "SSM, custom script, or CloudWatch Agent / logs.",
            "success_criteria": "Service status = running",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 9,
            "category": "Dependency",
            "code": "ec2_to_rds_connectivity",
            "check_item": "EC2 to RDS connectivity",
            "what_to_verify": "The server can reach its database endpoint and port.",
            "how_to_check": "TCP probe from the EC2 instance; optionally DB login using a health user.",
            "success_criteria": "Connection succeeds",
            "priority": "P1",
            "frequency": "1 to 5 min",
        },
        {
            "sort_order": 10,
            "category": "Dependency",
            "code": "ec2_to_s3_access",
            "check_item": "EC2 to S3 access",
            "what_to_verify": "The instance role and network path allow bucket access.",
            "how_to_check": "HeadBucket / HeadObject / GetObject / PutObject using the instance role.",
            "success_criteria": "Read/write test succeeds",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 11,
            "category": "Dependency",
            "code": "ec2_to_other_dependencies",
            "check_item": "EC2 to other dependencies",
            "what_to_verify": "The server can reach internal services, caches, queues, or external APIs it depends on.",
            "how_to_check": "TCP/HTTP probe from the instance or a close network vantage point.",
            "success_criteria": "Connection / response succeeds",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 12,
            "category": "Performance",
            "code": "cpu_utilization",
            "check_item": "CPU utilization",
            "what_to_verify": "The instance is not CPU saturated.",
            "how_to_check": "CloudWatch CPUUtilization.",
            "success_criteria": "Within baseline / below alert threshold",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 13,
            "category": "Performance",
            "code": "memory_usage",
            "check_item": "Memory usage",
            "what_to_verify": "Enough RAM is available to avoid swapping or OOM conditions.",
            "how_to_check": "CloudWatch Agent memory metrics.",
            "success_criteria": "Healthy free memory / below threshold",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 14,
            "category": "Capacity",
            "code": "disk_space_usage",
            "check_item": "Disk space usage",
            "what_to_verify": "Important filesystems are not close to full.",
            "how_to_check": "CloudWatch Agent disk_used_percent or OS script.",
            "success_criteria": "Below threshold (for example < 80 to 85%)",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 15,
            "category": "Performance",
            "code": "disk_ebs_io",
            "check_item": "Disk / EBS I/O",
            "what_to_verify": "Storage I/O is not stalled or saturated.",
            "how_to_check": "EBS metrics, diskio metrics, or OS metrics.",
            "success_criteria": "No sustained queueing / latency spike",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 16,
            "category": "Traffic",
            "code": "network_in_out_baseline",
            "check_item": "Network in / out baseline",
            "what_to_verify": "Traffic pattern is normal for the role of the server.",
            "how_to_check": "CloudWatch NetworkIn / NetworkOut.",
            "success_criteria": "Within expected baseline",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 17,
            "category": "Observability",
            "code": "recent_critical_errors",
            "check_item": "Recent critical errors",
            "what_to_verify": "The host and application are not producing repeated critical errors.",
            "how_to_check": "CloudWatch Logs, application logs, OS logs.",
            "success_criteria": "No recent critical error burst",
            "priority": "P2",
            "frequency": "5 to 15 min",
        },
    ],
    "rds": [
        {
            "sort_order": 1,
            "category": "Availability",
            "code": "db_instance_status",
            "check_item": "DB instance status",
            "what_to_verify": "The database resource is in a usable state.",
            "how_to_check": "RDS DBInstanceStatus.",
            "success_criteria": "Status = available",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 2,
            "category": "Maintenance",
            "code": "pending_maintenance_status",
            "check_item": "Pending maintenance status",
            "what_to_verify": "No required maintenance is waiting unnoticed.",
            "how_to_check": "Maintenance column / DescribePendingMaintenanceActions.",
            "success_criteria": "None, or planned and understood",
            "priority": "P2",
            "frequency": "15 to 60 min",
        },
        {
            "sort_order": 3,
            "category": "Accessibility",
            "code": "endpoint_dns_resolution",
            "check_item": "Endpoint DNS resolution",
            "what_to_verify": "The DB endpoint resolves correctly.",
            "how_to_check": "DNS lookup of the RDS endpoint.",
            "success_criteria": "DNS resolution succeeds",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 4,
            "category": "Accessibility",
            "code": "port_connectivity_from_app_servers",
            "check_item": "Port connectivity from app servers",
            "what_to_verify": "Each app EC2 can reach the DB port.",
            "how_to_check": "TCP probe from app servers to endpoint:port.",
            "success_criteria": "Connect succeeds within timeout",
            "priority": "P1",
            "frequency": "1 to 5 min",
        },
        {
            "sort_order": 5,
            "category": "Application",
            "code": "db_login",
            "check_item": "DB login",
            "what_to_verify": "The database listener accepts authenticated connections.",
            "how_to_check": "Connection attempt using a read-only health account.",
            "success_criteria": "Login succeeds",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 6,
            "category": "Application",
            "code": "simple_query",
            "check_item": "Simple query",
            "what_to_verify": "The engine can answer a minimal query.",
            "how_to_check": "Run SELECT 1 (or engine-equivalent).",
            "success_criteria": "Query returns expected result",
            "priority": "P1",
            "frequency": "1 min",
        },
        {
            "sort_order": 7,
            "category": "Performance",
            "code": "cpu_utilization",
            "check_item": "CPU utilization",
            "what_to_verify": "The DB is not CPU bound.",
            "how_to_check": "CloudWatch CPUUtilization.",
            "success_criteria": "Within baseline / below alert threshold",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 8,
            "category": "Performance",
            "code": "freeable_memory",
            "check_item": "Freeable memory",
            "what_to_verify": "The DB has enough available memory.",
            "how_to_check": "CloudWatch FreeableMemory.",
            "success_criteria": "Healthy headroom available",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 9,
            "category": "Capacity",
            "code": "free_storage_space",
            "check_item": "Free storage space",
            "what_to_verify": "The DB is not approaching storage-full state.",
            "how_to_check": "CloudWatch FreeStorageSpace.",
            "success_criteria": "Healthy free space / above alert threshold",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 10,
            "category": "Load",
            "code": "database_connections",
            "check_item": "Database connections",
            "what_to_verify": "Connection count is normal and below engine limits.",
            "how_to_check": "CloudWatch DatabaseConnections.",
            "success_criteria": "Within expected range",
            "priority": "P2",
            "frequency": "1 to 5 min",
        },
        {
            "sort_order": 11,
            "category": "Performance",
            "code": "disk_queue_depth",
            "check_item": "Disk queue depth",
            "what_to_verify": "I/O backlog is not building up.",
            "how_to_check": "CloudWatch DiskQueueDepth.",
            "success_criteria": "Low / stable queue depth",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 12,
            "category": "Performance",
            "code": "read_latency",
            "check_item": "Read latency",
            "what_to_verify": "Read I/O remains responsive.",
            "how_to_check": "CloudWatch ReadLatency.",
            "success_criteria": "Low / stable latency",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 13,
            "category": "Performance",
            "code": "write_latency",
            "check_item": "Write latency",
            "what_to_verify": "Write I/O remains responsive.",
            "how_to_check": "CloudWatch WriteLatency.",
            "success_criteria": "Low / stable latency",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 14,
            "category": "Replication",
            "code": "replica_lag",
            "check_item": "Replica lag",
            "what_to_verify": "Read replicas or readers are current enough for your SLA.",
            "how_to_check": "CloudWatch ReplicaLag.",
            "success_criteria": "Low / expected lag",
            "priority": "P1",
            "frequency": "1 to 5 min",
        },
        {
            "sort_order": 15,
            "category": "Traffic",
            "code": "network_throughput",
            "check_item": "Network throughput",
            "what_to_verify": "Database traffic level is normal for the workload.",
            "how_to_check": "CloudWatch NetworkReceiveThroughput / NetworkTransmitThroughput.",
            "success_criteria": "Within expected baseline",
            "priority": "P3",
            "frequency": "5 min",
        },
        {
            "sort_order": 16,
            "category": "Observability",
            "code": "enhanced_monitoring_os_metrics",
            "check_item": "Enhanced Monitoring / OS metrics",
            "what_to_verify": "The underlying OS is not showing pressure such as high swap or resource exhaustion.",
            "how_to_check": "Enhanced Monitoring metrics in CloudWatch Logs.",
            "success_criteria": "No critical OS pressure",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 17,
            "category": "Observability",
            "code": "db_logs_recent_errors",
            "check_item": "DB logs / recent errors",
            "what_to_verify": "The engine is not producing repeated errors, failed auth bursts, or slow query spikes.",
            "how_to_check": "CloudWatch Logs exports / engine logs / EventBridge.",
            "success_criteria": "No recent critical DB errors",
            "priority": "P2",
            "frequency": "5 to 15 min",
        },
    ],
    "s3": [
        {
            "sort_order": 1,
            "category": "Availability",
            "code": "bucket_access",
            "check_item": "Bucket access",
            "what_to_verify": "The bucket exists and is accessible with the expected credentials.",
            "how_to_check": "HeadBucket.",
            "success_criteria": "HTTP 200 OK",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 2,
            "category": "Accessibility",
            "code": "access_from_ec2_app_role",
            "check_item": "Access from EC2 / app role",
            "what_to_verify": "The actual runtime identity can access the bucket.",
            "how_to_check": "Run HeadBucket / Get / Put with the instance role or app role.",
            "success_criteria": "Operations succeed",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 3,
            "category": "Read",
            "code": "canary_metadata_check",
            "check_item": "Canary metadata check",
            "what_to_verify": "A known canary object is visible and readable at metadata level.",
            "how_to_check": "HeadObject on a small canary key.",
            "success_criteria": "HTTP 200 OK",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 4,
            "category": "Read",
            "code": "canary_content_read",
            "check_item": "Canary content read",
            "what_to_verify": "Object data can actually be read.",
            "how_to_check": "GetObject on the canary object.",
            "success_criteria": "Expected bytes/content returned",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 5,
            "category": "Write",
            "code": "canary_write",
            "check_item": "Canary write",
            "what_to_verify": "The bucket accepts writes.",
            "how_to_check": "PutObject of a tiny probe object.",
            "success_criteria": "Success response",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 6,
            "category": "Cleanup",
            "code": "canary_delete_overwrite",
            "check_item": "Canary delete / overwrite",
            "what_to_verify": "The probe object can be cleaned up safely.",
            "how_to_check": "DeleteObject or overwrite the probe according to your policy.",
            "success_criteria": "Cleanup succeeds",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 7,
            "category": "Listing",
            "code": "prefix_listing",
            "check_item": "Prefix listing",
            "what_to_verify": "If your app depends on listing, list operations work.",
            "how_to_check": "ListObjectsV2 on a probe prefix.",
            "success_criteria": "List succeeds",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 8,
            "category": "Errors",
            "code": "client_4xx_errors",
            "check_item": "4xx errors",
            "what_to_verify": "Valid requests are not failing due to auth or client issues.",
            "how_to_check": "CloudWatch 4xxErrors.",
            "success_criteria": "Near 0 for valid traffic",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 9,
            "category": "Errors",
            "code": "server_5xx_errors",
            "check_item": "5xx errors",
            "what_to_verify": "S3 server-side request failures are absent.",
            "how_to_check": "CloudWatch 5xxErrors.",
            "success_criteria": "0 server errors",
            "priority": "P1",
            "frequency": "5 min",
        },
        {
            "sort_order": 10,
            "category": "Performance",
            "code": "first_byte_latency",
            "check_item": "First byte latency",
            "what_to_verify": "Time to first byte remains normal.",
            "how_to_check": "CloudWatch FirstByteLatency.",
            "success_criteria": "Within baseline",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 11,
            "category": "Performance",
            "code": "total_request_latency",
            "check_item": "Total request latency",
            "what_to_verify": "End-to-end request time remains normal.",
            "how_to_check": "CloudWatch TotalRequestLatency.",
            "success_criteria": "Within baseline",
            "priority": "P2",
            "frequency": "5 min",
        },
        {
            "sort_order": 12,
            "category": "Traffic",
            "code": "request_volumes",
            "check_item": "Request volumes",
            "what_to_verify": "Request pattern matches what the application should be doing.",
            "how_to_check": "CloudWatch AllRequests / GetRequests / PutRequests / DeleteRequests / HeadRequests / ListRequests.",
            "success_criteria": "Within expected baseline",
            "priority": "P3",
            "frequency": "5 min",
        },
        {
            "sort_order": 13,
            "category": "Capacity",
            "code": "bucket_size",
            "check_item": "Bucket size",
            "what_to_verify": "Stored data growth is monitored.",
            "how_to_check": "CloudWatch BucketSizeBytes.",
            "success_criteria": "Within expected capacity trend",
            "priority": "P3",
            "frequency": "Daily",
        },
        {
            "sort_order": 14,
            "category": "Capacity",
            "code": "number_of_objects",
            "check_item": "Number of objects",
            "what_to_verify": "Object growth is monitored.",
            "how_to_check": "CloudWatch NumberOfObjects.",
            "success_criteria": "Within expected growth trend",
            "priority": "P3",
            "frequency": "Daily",
        },
        {
            "sort_order": 15,
            "category": "Replication",
            "code": "replication_backlog_failures",
            "check_item": "Replication backlog / failures",
            "what_to_verify": "If replication is enabled, it is current and healthy.",
            "how_to_check": "CloudWatch ReplicationLatency / BytesPendingReplication / OperationsPendingReplication / OperationsFailedReplication.",
            "success_criteria": "Low backlog and 0 failed operations",
            "priority": "P1",
            "frequency": "5 min",
        },
    ],
}

RESOURCE_SEEDS = [
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "services new live",
        "resource_identifier": "i-06c747d254aff01a0",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-15-206-144-38.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "15.206.144.38",
        "elastic_ip": "15.206.144.38",
        "metadata": {"instance_type": "t3a.medium", "security_groups": ["launch-wizard-13"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "products new Live",
        "resource_identifier": "i-0365361050856694e",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1a",
        "endpoint": "ec2-35-154-143-170.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "35.154.143.170",
        "elastic_ip": "35.154.143.170",
        "metadata": {"instance_type": "t3a.medium", "security_groups": ["launch-wizard-13"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "brands NEW live",
        "resource_identifier": "i-01c0d45242529d7d3",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-13-234-88-80.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "13.234.88.80",
        "elastic_ip": "13.234.88.80",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["launch-wizard-13"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "products new stage",
        "resource_identifier": "i-06ca254b01f811c11",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1a",
        "endpoint": "ec2-13-234-154-28.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "13.234.154.28",
        "elastic_ip": "13.234.154.28",
        "metadata": {"instance_type": "t3a.micro", "security_groups": ["launch-wizard-13"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "MessagingServer 2",
        "resource_identifier": "i-09cc95bb904221848",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-3-109-11-201.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "3.109.11.201",
        "elastic_ip": "3.109.11.201",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["launch-wizard-13"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "dalcamy, inditech, screeningservices and iaprichs",
        "resource_identifier": "i-03896d25209eb9405",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1a",
        "endpoint": "ec2-3-6-118-12.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "3.6.118.12",
        "elastic_ip": "3.6.118.12",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["launch-wizard-30"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "ticketing server (support.inditech)",
        "resource_identifier": "i-042b772db54dd2178",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-13-235-98-67.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "13.235.98.67",
        "elastic_ip": "13.235.98.67",
        "metadata": {"instance_type": "t3a.medium", "security_groups": ["launch-wizard-13"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "rfa_new",
        "resource_identifier": "i-089df33430adcda98",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-3-6-101-52.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "3.6.101.52",
        "elastic_ip": "3.6.101.52",
        "metadata": {"instance_type": "t2.small", "security_groups": ["launch-wizard-40"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "patient_portal new",
        "resource_identifier": "i-0075d53cf4fcbd7b4",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-35-154-221-92.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "35.154.221.92",
        "elastic_ip": "35.154.221.92",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["launch-wizard-41", "ec2-rds-1"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "nutrilift_new",
        "resource_identifier": "i-0cbf8e9781b3159d3",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-15-207-180-254.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "15.207.180.254",
        "elastic_ip": "15.207.180.254",
        "metadata": {"instance_type": "t3a.micro", "security_groups": ["launch-wizard-43"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "inclinic_new",
        "resource_identifier": "i-0026c4eab0c9631f7",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-13-200-145-110.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "13.200.145.110",
        "elastic_ip": "13.200.145.110",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["launch-wizard-44"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "EmoScreen_new",
        "resource_identifier": "i-033d0d38e4d69d659",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-3-108-245-139.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "3.108.245.139",
        "elastic_ip": "3.108.245.139",
        "metadata": {"instance_type": "t3a.medium", "security_groups": ["launch-wizard-45"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "forms live 1",
        "resource_identifier": "i-05547af7659e1abe0",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1a",
        "endpoint": "ec2-3-6-109-229.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "3.6.109.229",
        "elastic_ip": "3.6.109.229",
        "metadata": {"instance_type": "t3a.medium", "security_groups": ["launch-wizard-13"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "rfa content",
        "resource_identifier": "i-0a59a921adfe281c9",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1c",
        "endpoint": "ec2-65-2-42-240.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "65.2.42.240",
        "elastic_ip": "65.2.42.240",
        "metadata": {"instance_type": "t3a.micro", "security_groups": ["launch-wizard-48"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "Help PM Dashboard",
        "resource_identifier": "i-05c1e4f02f8245c2a",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1a",
        "endpoint": "ec2-65-1-101-252.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "65.1.101.252",
        "elastic_ip": "65.1.101.252",
        "metadata": {"instance_type": "t3.small", "security_groups": ["launch-wizard-52"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "Live Inclinic New",
        "resource_identifier": "i-0edb45221d5c9a8d3",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-43-205-154-138.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "43.205.154.138",
        "elastic_ip": "43.205.154.138",
        "metadata": {"instance_type": "t3.small", "security_groups": ["ec2-rds-2", "ec2-rds-3", "launch-wizard-47"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "Patient Portal Live",
        "resource_identifier": "i-0e8c135ffb5c8e3ae",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-65-0-143-171.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "65.0.143.171",
        "elastic_ip": "65.0.143.171",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["ec2-rds-2", "launch-wizard-49"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "RFA TS Low Live",
        "resource_identifier": "i-0f9991f836eea8c40",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-13-232-141-31.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "13.232.141.31",
        "elastic_ip": "13.232.141.31",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["ec2-rds-2", "launch-wizard-50"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "RFA TS High Live",
        "resource_identifier": "i-0171a0ed33cb4f722",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-43-205-175-230.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "43.205.175.230",
        "elastic_ip": "43.205.175.230",
        "metadata": {"instance_type": "t3a.xlarge", "security_groups": ["ec2-rds-2", "launch-wizard-50"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "reporting_server_new",
        "resource_identifier": "i-06a9a793950fa6eeb",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "ec2-13-126-7-118.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "13.126.7.118",
        "elastic_ip": "13.126.7.118",
        "metadata": {"instance_type": "t3a.small", "security_groups": ["ec2-rds-2", "launch-wizard-51", "ec2-rds-4"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "ec2",
        "account_id": ACCOUNT_ID,
        "name": "GPT VM",
        "resource_identifier": "i-0dc67b1fafcaec22c",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1a",
        "endpoint": "ec2-65-0-237-18.ap-south-1.compute.amazonaws.com",
        "public_ip_address": "65.0.237.18",
        "elastic_ip": "65.0.237.18",
        "metadata": {"instance_type": "t3a.medium", "security_groups": ["launch-wizard-53"], "platform_details": "Linux/UNIX"},
        "check_config": {},
    },
    {
        "service_type": "rds",
        "account_id": ACCOUNT_ID,
        "name": "master-db-new-system",
        "resource_identifier": "master-db-new-system",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "master-db-new-system.cbnobb8kfeuq.ap-south-1.rds.amazonaws.com",
        "port": 3306,
        "engine": "MySQL",
        "resource_state": "Available",
        "metadata": {
            "version": "8.4.7",
            "instance_class": "db.t3.small",
            "vcpu": 2,
            "ram": "2 GB",
            "storage": "20 GiB (gp3)",
            "multi_az": False,
            "vpc": "vpc-a3789ec8",
            "seed_cpu": 0.0436,
            "seed_connections": 0.0,
        },
        "check_config": {"db_probe": {"username_env": "", "password_env": "", "database_env": "", "port": 3306}},
    },
    {
        "service_type": "rds",
        "account_id": ACCOUNT_ID,
        "name": "new-forms-rds",
        "resource_identifier": "new-forms-rds",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "new-forms-rds.cbnobb8kfeuq.ap-south-1.rds.amazonaws.com",
        "port": 3306,
        "engine": "MySQL",
        "resource_state": "Available",
        "metadata": {
            "version": "8.0.44",
            "instance_class": "db.t3.micro",
            "vcpu": 2,
            "ram": "1 GB",
            "storage": "20 GiB (gp2)",
            "multi_az": False,
            "vpc": "vpc-a3789ec8",
            "seed_cpu": 0.0325,
            "seed_connections": 0.0,
        },
        "check_config": {"db_probe": {"username_env": "", "password_env": "", "database_env": "", "port": 3306}},
    },
    {
        "service_type": "rds",
        "account_id": ACCOUNT_ID,
        "name": "reporting-postgre-sql-live",
        "resource_identifier": "reporting-postgre-sql-live",
        "region": "ap-south-1",
        "availability_zone": "ap-south-1b",
        "endpoint": "reporting-postgre-sql-live.cbnobb8kfeuq.ap-south-1.rds.amazonaws.com",
        "port": 5432,
        "engine": "PostgreSQL",
        "resource_state": "Available",
        "metadata": {
            "version": "17.6",
            "instance_class": "db.t4g.micro",
            "vcpu": 2,
            "ram": "1 GB",
            "storage": "30 GiB (gp2)",
            "multi_az": False,
            "vpc": "vpc-a3789ec8",
            "seed_cpu": 0.0352,
            "seed_connections": 0.0,
        },
        "check_config": {"db_probe": {"username_env": "", "password_env": "", "database_env": "", "port": 5432}},
    },
    {
        "service_type": "s3",
        "account_id": ACCOUNT_ID,
        "name": "rfa-live",
        "resource_identifier": "rfa-live",
        "region": "ap-south-1",
        "endpoint": "arn:aws:s3:::rfa-live",
        "metadata": {
            "created_on": "2026-02-16",
            "versioning": "Disabled",
            "mfa_delete": "Disabled",
            "abac": "Disabled",
        },
        "check_config": {"canary_prefix": "aws-checker/probes/rfa-live"},
    },
    {
        "service_type": "s3",
        "account_id": ACCOUNT_ID,
        "name": "rfa-patient-reponses",
        "resource_identifier": "rfa-patient-reponses",
        "region": "ap-south-1",
        "endpoint": "arn:aws:s3:::rfa-patient-reponses",
        "metadata": {
            "created_on": "2026-01-03",
            "versioning": "Disabled",
            "mfa_delete": "Disabled",
            "abac": "Disabled",
        },
        "check_config": {"canary_prefix": "aws-checker/probes/rfa-patient-reponses"},
    },
]
