# Generated by Django 4.2.30 on 2026-04-19 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ec2', 'EC2'), ('rds', 'RDS'), ('s3', 'S3')], max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('category', models.CharField(max_length=64)),
                ('code', models.SlugField(max_length=100)),
                ('check_item', models.CharField(max_length=255)),
                ('what_to_verify', models.TextField()),
                ('how_to_check', models.TextField()),
                ('success_criteria', models.TextField()),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=2)),
                ('frequency', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_type', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail'), ('skip', 'Skipped'), ('error', 'Error')], max_length=10)),
                ('summary', models.TextField()),
                ('observed_value', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['resource__name', 'check_definition__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('resource', 'Single resource'), ('service', 'Single service'), ('all', 'All services')], max_length=12)),
                ('label', models.CharField(max_length=255)),
                ('service_type', models.CharField(blank=True, choices=[('ec2', 'EC2'), ('rds', 'RDS'), ('s3', 'S3')], max_length=10)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail'), ('skip', 'Skipped'), ('error', 'Error')], default='warn', max_length=10)),
                ('resource_count', models.PositiveIntegerField(default=0)),
                ('check_count', models.PositiveIntegerField(default=0)),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('warn_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_from', models.CharField(blank=True, default='ui', max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManagedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='736616688306', max_length=32)),
                ('service_type', models.CharField(choices=[('ec2', 'EC2'), ('rds', 'RDS'), ('s3', 'S3')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('resource_identifier', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=32)),
                ('availability_zone', models.CharField(blank=True, max_length=32)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('public_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('elastic_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=64)),
                ('resource_state', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_config', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_overall_status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail'), ('skip', 'Skipped'), ('error', 'Error')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='managedresource',
            constraint=models.UniqueConstraint(fields=('service_type', 'resource_identifier'), name='unique_service_resource_identifier'),
        ),
        migrations.AddField(
            model_name='checkrun',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='checker.managedresource'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='check_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='checker.checkdefinition'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_results', to='checker.managedresource'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checker.checkrun'),
        ),
        migrations.AddConstraint(
            model_name='checkdefinition',
            constraint=models.UniqueConstraint(fields=('service_type', 'code'), name='unique_check_code_per_service'),
        ),
    ]
